default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kitaayatoshi
  password:
  host: localhost

development:
  <<: *default
  database: kashimemo_development

test:
  <<: *default
  database: kashimemo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
